import type { CreateRulePayload } from '@/api/bot'

export const MEGA_PROMPT_200_AUTO_REPLIES = `### PERAN & TUJUAN
Kamu adalah Pakar Percakapan WhatsApp (WhatsApp Interaction Designer & Copywriter Indonesia) yang memiliki kemampuan empati linguistik tinggi.
Tugasmu adalah menganalisis DUA BERKAS LAMPIRAN CHAT WHATSAPP yang kuunggah:
1. "PENCARI LOKER.zip" (Berisi riwayat chat tongkrongan pemuda Medan / Sumatera Utara bersama Eka Syarif Maulana S.Kom dan rekan-rekannya).
2. "Indah 🧕🌿💝.zip" (Berisi riwayat chat personal bersama INDAH, pacar tercinta dari Eka Syarif Maulana dengan nomor WhatsApp +62 852-1614-9732).

Berdasarkan analisis kedua berkas tersebut, tugas utamamu adalah menghasilkan DATA DUMP 200 ATURAN BALASAN OTOMATIS (Auto-Reply Rules) dalam format JSON Array murni yang 100% cocok untuk di-import langsung ke sistem WhatsApp Bot kami.

---

### ANALISIS GAYA BAHASA DARI DUA SUMBER (WAJIB DITERAPKAN)

1. REFERENSI SUMBER 1: "PENCARI LOKER.zip" (Gaya Chat Teman, Tongkrongan & Sehari-hari):
   - Persona: Eka Syarif Maulana S.Kom (lulusan TI UMSU Medan), santai, ceplas-ceplos, cerdas, solutif, akrab, humoris.
   - Kosakata & Logat: Santai khas Medan / Sumatera Utara gaul ("klen/kelen", "cok", "bjir", "njir", "gess", "kali/kli", "gaspol", "omke gas", "modals sikit", "santai aja", "pigi", "jumpalah", "wkwkwk").
   - Tone: Sangat santai, tidak pernah kaku, responsif, bersahabat, to the point.

2. REFERENSI SUMBER 2: "Indah 🧕🌿💝.zip" (Gaya Chat Personal Khusus Pacar: Indah +62 852-1614-9732):
   - Persona terhadap Indah: Eka sebagai pasangan / pacar yang penuh perhatian, hangat, lembut, menyayangi, dan humoris romantis santai.
   - Topik & Diksi: Panggilan manis ("sayang", "ndah", "ayang", "beb"), perhatian sehari-hari ("udah makan belum?", "lagi apa sayang?", "jangan begadang ya", "udah sholat belum?", "semangat ya hari ini ❤️", "kangen nih", "nanti kita jalan ya").
   - DILARANG KERAS merespon Indah seperti robot atau CS formal. Respon harus terdengar seperti pacar asli yang sedang membalas chat WhatsApp-nya!

---

### STRUKTUR PEMBAGIAN 200 PEMICU (JSON):
- Kategori A: 150 Pemicu Umum, Teman & Pelanggan (Adopsi gaya dari PENCARI LOKER):
  1. Sapaan Waktu & Salam (Pagi, Siang, Malam, Halo, Assalamualaikum, Oy, Woi, dll. - 25 pemicu)
  2. Sapaan Singkat & Panggilan (P, Ping, Tes, Min, Gan, Bro, Mas, Lur, dll. - 25 pemicu)
  3. Tanya Keberadaan & Jam Operasional (Buka gak, Ada orang, Online gak, dll. - 20 pemicu)
  4. Tanya Kabar & Obrolan Santai (Apa kabar, Sehat, Lagi sibuk ya, dll. - 20 pemicu)
  5. Tanya Layanan, Harga & Order (Berapaan, Ada diskon, Cara order, dll. - 20 pemicu)
  6. Pembayaran, Lokasi & Pengiriman (Bisa transfer, Minta rek, Lokasi mana, dll. - 20 pemicu)
  7. Terima Kasih, Candaan & Ngopi (Makasih bro, Mantap jiwa, Ngopi dulu, Wkwk, dll. - 20 pemicu)

- Kategori B: 50 Pemicu Khusus Personal / Pasangan (Adopsi gaya dari Indah 🧕🌿💝):
  1. Sapaan Sayang & Panggilan Mesra (Sayang, Ayang, Ndah, Beb, Cinta, dll. - 10 pemicu)
  2. Perhatian Rutinitas Harian (Udah makan belum, Lagi ngapain sayang, Jangan begadang, Istirahat ya, dll. - 10 pemicu)
  3. Semangat & Dukungan (Semangat kerjanya, Semangat ya hari ini, Sukses ya sayang, dll. - 10 pemicu)
  4. Sapaan Waktu Khusus Pasangan (Pagi sayang, Malam ayang, Good night sayang, Mimpi indah ya, dll. - 10 pemicu)
  5. Candaan Manja & Rindu (Kangen nih, Ngambek ya, Love you, Jemput ya sayang, dll. - 10 pemicu)

---

### ATURAN FORMAT OUTPUT (RAW JSON ARRAY MURNI):
- Hasilkan HANYA valid JSON Array tanpa teks pengantar, penutup, atau markdown pembungkus di luar JSON.
- Struktur setiap objek:
  {
    "trigger_type": "contains", // atau "exact"
    "trigger_value": "<kata_kunci>",
    "recipient_jid": "6285216149732@s.whatsapp.net", // WAJIB: Isi '6285216149732@s.whatsapp.net' KHUSUS untuk Kategori B (Pacar Indah), atau kosongkan "" untuk Kategori A (Umum/Global)
    "scope": "all",
    "response_type": "text",
    "response_content": "<teks_balasan_sesuai_analisis>",
    "is_active": true
  }

Sekarang, baca kedua berkas yang kuunggah ("PENCARI LOKER.zip" & "Indah 🧕🌿💝.zip"), dan hasilkan 200 data objek JSON lengkap tersebut!`

export const DEFAULT_200_AUTO_REPLIES: CreateRulePayload[] = [
  // 1. Sapaan & Waktu (1-20)
  {
    trigger_type: 'contains',
    trigger_value: 'selamat pagi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pagi juga bro! Semangat jalanin hari ini ya ☕ Ada yang bisa dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'pagi kak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pagi kak! Udah ngopi belum nih? Semoga harimu menyenangkan ya ✨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'selamat siang',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siang juga! Panas-panas gini jangan lupa minum ya. Mau nanya apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'siang min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siang kak! Lagi istirahat siang ya? Santai aja, ada yang mau ditanyain?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'selamat sore',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sore juga sob! Jam-jam santai nih, gimana harinya lancar kan?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'sore kak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sore kak! Sebentar lagi kelar nih rutinitas hari ini, ada yang mau dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'selamat malam',
    scope: 'all',
    response_type: 'text',
    response_content: 'Malam bro! Masih melek aja nih hehe. Ada yang perlu dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'malam min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Malam kak! Santai aja, kalau mau ninggalin pesan langsung tulis di sini ya 🌙',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'assalamualaikum',
    scope: 'all',
    response_type: 'text',
    response_content: 'Waalaikumsalam warahmatullahi wabarakatuh! Halo kak, apa kabar? Ada yang bisa dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'assalamu alaikum',
    scope: 'all',
    response_type: 'text',
    response_content: 'Waalaikumsalam kak! Berkah selalu ya. Mau cek apa hari ini?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'samlikum',
    scope: 'all',
    response_type: 'text',
    response_content: 'Waalaikumsalam bro! Santai bener salamnya haha, ada apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'halo',
    scope: 'all',
    response_type: 'text',
    response_content: 'Halo juga! Selamat datang, kabarin aja ya kalau mau tanya-tanya 🙌',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hello',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hello there! Ada yang bisa kubantu hari ini? Tulis aja ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hai kak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hai kak! Senang dichat nih, ada info apa yang lagi dicari?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hey bro',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yoi bro! Ada apa nih sob? Santai aja obrolin di sini.',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'oy',
    scope: 'all',
    response_type: 'text',
    response_content: 'Oy juga! Tumben mampir, ada urusan apa nih? 😁',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'woi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Woi santai napa haha! Ada apa nih manggil-manggil?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'shalom',
    scope: 'all',
    response_type: 'text',
    response_content: 'Shalom kak! Damai sejahtera beserta kita. Ada yang bisa dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kulonuwun',
    scope: 'all',
    response_type: 'text',
    response_content: 'Monggo kak! Sugeng rawuh, wonten nopo nggih? Pinarak rumiyin.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'sampurasun',
    scope: 'all',
    response_type: 'text',
    response_content: 'Rampes kang! Damang? Aya naon yeuh, mangga dibantos 🙏',
    is_active: true,
  },

  // 2. Sapaan Singkat & Panggilan (21-40)
  {
    trigger_type: 'exact',
    trigger_value: 'p',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya hadir! P doang nih? Langsung to the point aja kak mau tanya apa haha ✌️',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'ping',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pong! 🏓 Sinyal aman terkendali. Mau bahas apa kita hari ini?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'test',
    scope: 'all',
    response_type: 'text',
    response_content: 'Masuk kok pesannya! Mic cek 1 2 3, suara terdengar jelas. Ada apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'tes',
    scope: 'all',
    response_type: 'text',
    response_content: 'Tes berhasil! Respon jalan lancar jaya. Ada yang mau dibantu bro?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'admin',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap hadir kak! Admin di sini, ada yang urgent atau mau konsultasi?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yaa kak, hadir! Boleh langsung ceritain mau nanya apa ya.',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'gan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yoi juragan! Ada proyek atau pesanan apa yang bisa dibantu nih?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'bro',
    scope: 'all',
    response_type: 'text',
    response_content: 'Wassup bro! Aman kan? Ada kabar apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'sis',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hai siss! Ada yang lagi kamu incer ya? Sini aku bantu spill.',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'om',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya siap om! Berasa senior nih dipanggil om hehe. Ada apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: 'kak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya kak? Kenapa tuh? Tulis aja ya unek-unek atau pertanyaannya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'permisi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya monggo kak, silakan banget! Langsung tulis aja keperluannya ya 🙏',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'numpang tanya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Boleh banget dong, nanya gratis kok gak bayar hehe. Tanya apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'mau nanya dong',
    scope: 'all',
    response_type: 'text',
    response_content: 'Boleh banget kak! Mau nanya seputar apa? Langsung ketik di sini aja ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'boleh tanya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Boleh banget kak, santai aja! Mau tanya apa nih? Pasti kujawab kok.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'misi min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya kak misi diterima! Mau ada yang dicek atau dibeli nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'mon maap',
    scope: 'all',
    response_type: 'text',
    response_content: 'Santai aja bro gak usah minta maaf segala haha. Ada apa gerangan?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'punten',
    scope: 'all',
    response_type: 'text',
    response_content: 'Mangga kang/teh! Aya naon? Boleh langsung ditaroskeun wae nya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'permisi gan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap gan! Silakan masuk, ada info apa yang agan butuhin?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'spada',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yaaa siapa di luar? Pintu gak dikunci kok, langsung masuk aja haha! Ada apa nih?',
    is_active: true,
  },

  // 3. Keberadaan & Jam Operasional (41-60)
  {
    trigger_type: 'contains',
    trigger_value: 'ada orang',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada dong kak, masih manusia asli yang standby kok! Mau tanya apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'masih buka',
    scope: 'all',
    response_type: 'text',
    response_content: 'Masih buka kak! Chat aja terus, selama belum tidur pasti dibales kok 🚀',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'buka jam berapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kita biasa aktif jam 08.00 pagi sampai 22.00 WIB ya kak. Tapi chat masuk 24 jam tetep kita tampung!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'tutup jam berapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pelayanan santai biasanya sampai jam 22.00 WIB kak. Lewat dari itu dibales besok pagi ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'masih online',
    scope: 'all',
    response_type: 'text',
    response_content: 'Masih dong! Mata masih melek kopi masih anget nih. Mau nanya apa?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi sibuk ga',
    scope: 'all',
    response_type: 'text',
    response_content: 'Gak kok, santai aja! Ada hal menarik apa nih yang mau diceritain/ditanyain?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa fast respon',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap kita usahain secepat kilat kak! Langsung tulis aja ya pertanyaannya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bot ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hehe sistem balasan otomatis ada, tapi admin aslinya juga baca kok! Mau ngobrol langsung?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ini bot',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya ini asisten otomatis yang siap nemenin kamu 24/7! Mau nanya menu apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'orang asli bukan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Orang asli yang dipersenjatai teknologi canggih biar kamu gak nunggu lama kak 😁',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi off ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi stand by kok kak! Tulis aja pesannya, langsung kubaca sekarang.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hari ini buka',
    scope: 'all',
    response_type: 'text',
    response_content: 'Buka terus kak, pantang libur selama masih ada orderan masuk hehe. Gass order!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minggu buka gak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hari minggu kita tetap melayani chat dan pesanan kok kak, slow respon dikit ya tapi pasti dibalas!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'libur ga',
    scope: 'all',
    response_type: 'text',
    response_content: 'Tanggal merah tetap buka santai kak! Kamu mau order atau tanya apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada cs',
    scope: 'all',
    response_type: 'text',
    response_content: 'CS standby kak! Boleh langsung infokan keluhannya atau mau tanya seputar apa ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ready min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ready banget kak! Tinggal bilang aja mau yang mana, langsung kita proses ⚡',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ready ga',
    scope: 'all',
    response_type: 'text',
    response_content: 'Stok ready kak! Mau yang tipe apa nih? Biar langsung dicek detailnya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'masih ada stok',
    scope: 'all',
    response_type: 'text',
    response_content: 'Masih aman stoknya kak! Tapi jangan kelamaan ya, takut diserbu yang lain hehe.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'habis ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Coba sebutin mau barang/layanan apa kak? Biar ku cekin sisa kuotanya ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kapan restock',
    scope: 'all',
    response_type: 'text',
    response_content: 'Biasa dalam 2-3 hari ke depan udah masuk lagi kak. Mau diinfoin pas udah ready?',
    is_active: true,
  },

  // 4. Tanya Kabar & Keadaan (61-80)
  {
    trigger_type: 'contains',
    trigger_value: 'apa kabar',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kabar baik banget kak, makasih udah nanya! Kamu gimana, sehat dan lancar rezekinya kan? ✨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'sehat bro',
    scope: 'all',
    response_type: 'text',
    response_content: 'Alhamdulillah sehat walafiat sob! Lu gimana kabarnya? Jangan lupa jaga kesehatan ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi apa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi mantengin chat sambil nungguin kabar baik dari kamu nih haha. Ada apa sob?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah makan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Udah dong, perut kenyang hati senang! Kamu jangan sampai telat makan ya kak 🍛',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi ngapain',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi standby bantuin temen-temen yang mau tanya seputar produk/layanan nih. Ada yang mau ditanyain?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'capek ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Capek itu manusiawi, tapi dichat sama kamu langsung seger lagi kok haha! Semangat ya!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah tidur',
    scope: 'all',
    response_type: 'text',
    response_content: 'Belum tidur nih! Masih melek jagain notifikasi chat. Ada hal darurat kak?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi di mana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi di depan layar nih setia nungguin kamu haha. Ada perlu apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kangen nih',
    scope: 'all',
    response_type: 'text',
    response_content: 'Waduh kangen sama siapa nih? Kalo kangen promo langsung gas order aja dong wkwk 😜',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'siapa nih',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ini asisten WhatsApp resmi kak! Senang kenalan sama kamu, ada yang mau dibantu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kenal aku ga',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kenal dong! Dari username WhatsApp kamu aja udah keliatan orang keren kok 😎',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kamu siapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Aku asisten bot WhatsApp yang selalu setia ngebantuin kamu 24 jam. Mau tanya apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'namamu siapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Panggil aja Mimin atau Bro Bot! Santai aja panggil senyamannya ya 🙌',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'umur berapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Umurku masih muda banget, tapi ilmu dan responnya udah senior kok hehe!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'tinggal di mana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Tinggal di dunia digital yang siap meluncur ke layar HP kamu kapan pun dipanggil 🚀',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hobi apa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Hobiku balas chat kamu secepat mungkin biar kamu gak digantungin orang lain wkwk!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah punya pacar',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pacarku cuma internet kenceng sama server stabil kak haha! Mau order apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ngopi yuk',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kopi hitam tanpa gula mantap tuh ☕ Kirim lewat ojol sini kalau beneran haha!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bosen nih',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kalo bosen mending cuci mata liat produk kita kak, siapa tau ada yang cocok di hati ✨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'gabut ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Haha gak gabut kok, ini lagi fokus nungguin chat kamu masuk!',
    is_active: true,
  },

  // 5. Tanya Produk, Jasa & Katalog (81-100)
  {
    trigger_type: 'contains',
    trigger_value: 'liat katalog',
    scope: 'all',
    response_type: 'text',
    response_content: 'Boleh kak! Untuk katalog lengkap dan varian terupdate langsung cek di daftar menu kita ya. Mau cari yang mana?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada barang apa aja',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kita punya banyak pilihan kak! Mulai dari yang best seller sampai yang lagi promo. Kasih tau aja budget atau seleramu.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'spill produk',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap dispill! Yang paling laku minggu ini banyak dicari orang kak. Mau liat foto atau speknya dulu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada pricelist',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada dong kak! Pricelist lengkapnya udah siap, kamu mau cek untuk paket hemat atau yang premium nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minta menu',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ini menunya kak! Silakan dilihat-lihat dulu ya, kalau ada yang bikin naksir langsung bilang aja 📋',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'rekomendasi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kalo rekomendasi dari Mimin sih ambil paket paling populer kak, fiturnya lengkap harganya paling pas di kantong!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'yang paling laris',
    scope: 'all',
    response_type: 'text',
    response_content: 'Varian favorit pelanggan itu yang edisi best seller kak! Dijamin puas dan banyak yang repeat order.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'best seller',
    scope: 'all',
    response_type: 'text',
    response_content: 'Juara bertahannya ada di paket utama kak! Sering kehabisan slot juga, mumpung ready buruan diamanin ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada garansi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pasti ada garansi dong kak! Kualitas dan kepuasan kamu prioritas nomor satu buat kita. Syaratnya gampang banget.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kualitasnya gimana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kualitas terjamin joss kak! Kita selalu lewatin quality control ketat sebelum dikirim ke kamu.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ori gak',
    scope: 'all',
    response_type: 'text',
    response_content: '100% Original dan resmi kak! Gak main yang abal-abal, kepuasan kamu taruhannya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'asli bukan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Asli dong kak, garansi uang kembali kalau barangnya palsu! Amanah nomor satu.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa custom',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget dicustom sesuai request kamu kak! Kirim aja detail atau referensinya ke sini ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada foto asli',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada kak! Real pict tanpa editan lebay. Tunggu sebentar ku siapin fotonya ya 📸',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa liat video',
    scope: 'all',
    response_type: 'text',
    response_content: 'Boleh kak, nanti dikirimin video review detail biar makin mantep milihnya ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada review',
    scope: 'all',
    response_type: 'text',
    response_content: 'Banyak testi dan review positif dari pelanggan kak! Rata-rata bintang 5, mau liat tangkapan layarnya?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'testimoni',
    scope: 'all',
    response_type: 'text',
    response_content: 'Testi melimpah kak! Pelanggan pada puas sama respon cepat dan barangnya. Tenang aja aman 100%.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa dropship',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa dropship kak! Nama pengirim atas nama toko kamu, tanpa resi/logo kita. Cuan bareng yuk!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada reseller',
    scope: 'all',
    response_type: 'text',
    response_content: 'Peluang reseller sangat terbuka kak! Ada harga khusus buat yang mau join jadi partner kita.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'harga grosir',
    scope: 'all',
    response_type: 'text',
    response_content: 'Beli banyak pasti dapet diskon gede kak! Makin banyak qty-nya, harganya makin miring.',
    is_active: true,
  },

  // 6. Tanya Harga & Promo (101-120)
  {
    trigger_type: 'contains',
    trigger_value: 'berapaan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Harganya ramah banget di kantong kak! Mulai dari harga hemat sampai paket komplit. Mau yang mana?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'berapa harganya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Harganya bersahabat kok kak! Coba sebutkan tipe yang kamu suka biar kubisikin harga pasnya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'harganya berapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Murah meriah berkualitas kak! Mau harga satuan atau harga grosiran nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada diskon',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi ada potongan harga khusus nih kak! Khusus buat kamu yang order hari ini ada voucher spesial 🔥',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada promo',
    scope: 'all',
    response_type: 'text',
    response_content: 'Promo hari ini lagi mantep kak! Beli paket tertentu dapet bonus langsung. Mau ku infoin detailnya?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa nego',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa diatur tipis-tipis kak asal sama-sama cocok haha! Mau ambil berapa banyak nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kemahalan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada harga ada kualitas kak! Tapi tenang, kita punya opsi paket hemat yang gak kalah bagus kok.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada yang lebih murah',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada paket versi lite kak! Fitur utamanya tetep dapet tapi harganya lebih miring. Mau liat?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah nett',
    scope: 'all',
    response_type: 'text',
    response_content: 'Harga terbaik yang kita tawarin udah nett kak, tapi nanti dapet bonus ekstra dari mimin deh!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'harga pas',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya kak, ini harga pas paling worth it se-Indonesia. Langsung angkut yuk!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'biaya berapa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Biayanya transparan tanpa ada biaya siluman kak. Coba kasih tau kebutuhanmu apa aja.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'gratis gak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Konsultasi sama tanya-tanya 100% gratis kak! Kalo barangnya tentu bayar dong biar berkah hehe ✌️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ongkir gratis',
    scope: 'all',
    response_type: 'text',
    response_content: 'Untuk pembelian minimal tertentu ada subsidi free ongkir kak! Kasih tau lokasi kamu ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada cashback',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada promo cashback poin/potongan langsung kak! Pas banget kamu nanya pas lagi jalan promonya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'voucher',
    scope: 'all',
    response_type: 'text',
    response_content: 'Masih ada kuota voucher hemat kak! Ketik MAUORDER biar langsung mimin aktifin vouchernya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'flash sale',
    scope: 'all',
    response_type: 'text',
    response_content: 'Flash sale sering kita adain kak! Biar gak ketinggalan, pantengin terus chat di sini ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bonusnya apa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bonusnya banyak kejutan menarik kak, dari free gift sampai stiker keren. Mau langsung checkout?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa cicil',
    scope: 'all',
    response_type: 'text',
    response_content: 'Untuk cicilan bisa lewat platform mitra resmi atau paylater kak. Aman dan terpercaya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa dp',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa DP 50% dulu untuk tanda jadi kak! Pelunasan pas barang udah siap kirim.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minimal order',
    scope: 'all',
    response_type: 'text',
    response_content: 'Gak ada minimal order kok kak, pesan 1 biji pun tetep kita layani sepenuh hati ❤️',
    is_active: true,
  },

  // 7. Cara Order & Format Pesanan (121-140)
  {
    trigger_type: 'contains',
    trigger_value: 'cara belinya gimana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Gampang banget kak! Kamu tinggal ketik nama barang yang mau dipesan, alamat, dan nomor HP. Nanti mimin buatkan totalannya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'cara order',
    scope: 'all',
    response_type: 'text',
    response_content: 'Alur order gampang: 1. Pilih barang, 2. Kirim format order, 3. Bayar, 4. Langsung kita proses kirim 📦',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'mau pesen',
    scope: 'all',
    response_type: 'text',
    response_content: 'Asik! Mau pesen yang mana nih kak? Sebutin aja ya, biar langsung diamankan stoknya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'mau order',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap tampung orderan kak! Boleh diisi format pemesanannya ya biar cepet diproses.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'format order',
    scope: 'all',
    response_type: 'text',
    response_content: `Format Order Cepat:
- Nama Lengkap:
- Nomor HP:
- Alamat Lengkap:
- Pesanan & Jumlah:

Kirim ke sini ya kak biar langsung direkap!`,
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'format pesanan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Silakan ketik: [Nama] - [Kota/Kecamatan] - [Nama Barang] - [Jumlah]. Nanti langsung kita buatin invoice ya kak.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'booking slot',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget booking slot kak! Biar gak keduluan yang lain, mau keep untuk hari apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'keep dulu',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa kita keep maksimal 1x24 jam ya kak. Kalo udah fix mau bayar langsung kabari lagi ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa po',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa Pre-Order kak! Proses pengerjaan 3-5 hari kerja aja, hasil dijamin rapi dan memuaskan.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'berapa lama prosesnya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Proses kilat kak! Kalo barang ready langsung kirim di hari yang sama kalau checkout sebelum jam 15.00 WIB.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kapan dikirim',
    scope: 'all',
    response_type: 'text',
    response_content: 'Orderan masuk hari ini langsung disiapin dan masuk ekspedisi sore nanti ya kak 🛵',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minta invoice',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap kak, invoice resmi bakal langsung kita kirim begitu format order dan konfirmasi beres.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa nota',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa disertakan nota belanja fisik atau e-nota PDF kak. Kasih tau aja mau atas nama siapa ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa faktur pajak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa kak untuk pesanan corporate/instansi. Lampirkan NPWP perusahaan kamu ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ganti pesanan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa diganti selagi paket belum diserahkan ke kurir kak! Mau ganti ke varian apa nih?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'tambah pesanan',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget digabungin dalam 1 paket biar hemat ongkir kak! Mau tambah apa aja?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'batalin order',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yah kenapa dibatalin kak? Coba ceritain kendalanya, siapa tahu mimin bisa kasih solusi terbaik 🥺',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'cancel ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Oke kak pesanan dibatalkan. Semoga di lain kesempatan bisa belanja di sini lagi ya 🙏',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah fix ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Mantap sudah fix! Segera mimin rekap dan kirim totalannya ke sini ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'gas order',
    scope: 'all',
    response_type: 'text',
    response_content: 'Gasskeun bro! Langsung kirim alamatnya yuk biar langsung dipacking rapi 🚀',
    is_active: true,
  },

  // 8. Pembayaran & Rekening (141-160)
  {
    trigger_type: 'contains',
    trigger_value: 'bisa transfer',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget kak! Kita sedia transfer ke BCA, Mandiri, BRI, BNI, dan Bank Jago.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minta rek',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ini nomor rekening resmi kita ya kak: Silakan transfer dan jangan lupa kirim bukti struknya ke sini agar diverifikasi cepat 💳',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'no rekening',
    scope: 'all',
    response_type: 'text',
    response_content: 'Nomor rekening atas nama toko resmi kita kak. Mau transfer via bank apa biar mimin kirim nomornya?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'rekening bca',
    scope: 'all',
    response_type: 'text',
    response_content: 'BCA siap kak! Tunggu totalan final dulu ya biar gak salah nominal transfernya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'rekening mandiri',
    scope: 'all',
    response_type: 'text',
    response_content: 'Mandiri aktif kak! Nanti cantumkan berita transfer nama kamu ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'rekening bri',
    scope: 'all',
    response_type: 'text',
    response_content: 'BRI ready kak! Transaksi antar bank juga bebas biaya admin kalo pake BI Fast.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada qris',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ada QRIS kak! Bisa discan pakai aplikasi apa aja (GoPay, OVO, Dana, ShopeePay, BCA, dll). Praktis tanpa ribet.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa qris',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget! Nanti dikirim barcode QRIS langsung discan dari HP kamu ya 📲',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa dana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa lewat DANA kak! Nomor e-wallet aktif 24 jam.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa gopay',
    scope: 'all',
    response_type: 'text',
    response_content: 'GoPay ready kak! Scan QRIS atau transfer nomor HP bisa dua-duanya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa ovo',
    scope: 'all',
    response_type: 'text',
    response_content: 'OVO bisa juga kak! Bebas biaya tambahan.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa shopeepay',
    scope: 'all',
    response_type: 'text',
    response_content: 'ShopeePay bisa kak lewat scan barcode QRIS ya!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa cod',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa COD (Bayar di Tempat) kak! Asal alamat jelas dan nomor HP aktif pas kurir nganter ya 📦',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bayar di tempat',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa bayar pas paket sampai di rumah kak. Pastikan siapin uang pas ya pas kurir datang.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah transfer ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Alhamdulillah mantap kak! Boleh kirim foto struk/screenshot bukti transfernya ke sini ya biar langsung dicek.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ini buktinya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bukti transfer diterima kak! Dana sudah masuk, paket langsung masuk antrean packing prioritas ya 🚀',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah bayar min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sip terima kasih banyak kak! Pembayaran terverifikasi. Tunggu resi dari mimin ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ada biaya admin',
    scope: 'all',
    response_type: 'text',
    response_content: 'Tanpa biaya admin kak! Nominal yang kamu transfer sesuai dengan harga invoice pas.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'keamanan transaksi',
    scope: 'all',
    response_type: 'text',
    response_content: '100% Amanah dan terpercaya kak! Semua rekening dan kontak resmi diverifikasi.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa refund',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa refund jika terjadi kendala dari pihak kami atau stok tiba-tiba kosong kak. Uang kembali utuh.',
    is_active: true,
  },

  // 9. Lokasi, Pengiriman & Ongkir (161-180)
  {
    trigger_type: 'contains',
    trigger_value: 'lokasi di mana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Toko kita berlokasi di pusat kota kak. Kamu dari daerah mana nih? Kita bisa kirim ke seluruh pelosok Nusantara 🇮🇩',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'toko di mana',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kita beroperasi secara online dengan gudang pengiriman utama kak. Bisa kirim ekspedisi atau kurir instan.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa kirim ke luar kota',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget kak! Dari Sabang sampai Merauke siap kita kirim pakai packing aman berlapis bubble wrap tebal.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa pake gojek',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa kirim via GoSend/GrabExpress Instant kak! Pesan sekarang, 1-2 jam langsung sampai di depan pintu.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa same day',
    scope: 'all',
    response_type: 'text',
    response_content: 'Same day bisa kak! Batas order same day sebelum jam 13.00 WIB ya biar kekejar kurirnya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ekspedisi apa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kita kerjasama dengan J&T, JNE, SiCepat, Anteraja, dan Pos Indonesia. Mau pilih yang mana bebas kak.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'cek ongkir',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa dicek ongkirnya kak! Boleh sebutkan nama Kecamatan dan Kota tujuan kamu?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ongkir ke',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sip ditampung! Mimin cek tarif ongkir termurahnya dulu ya kak, tunggu 1 menit.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'packing aman ga',
    scope: 'all',
    response_type: 'text',
    response_content: 'Packing super aman kak! Pake kardus tebal + bubble wrap gratis tanpa biaya tambahan.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'minta resi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Nomor resi otomatis diupdate malam hari setelah semua paket discan oleh kurir ekspedisi ya kak.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'nomor resi',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap kak, begitu paket diserahin ke kurir resi bakal langsung difotoin ke chat ini ya 📄',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lacak paket',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa kak, kirim nomor resi kamu ke sini biar dibantu cek posisi paketnya ada di mana.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa ambil sendiri',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa ambil langsung (self pickup) kak! Janjian waktu dulu ya biar paketnya udah siap pas kamu datang.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'alamat lengkapnya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Alamat lengkap titik gudang kami bisa disharelok kak kalau mau berkunjung.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa share loc',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap kak, ditunggu ya lokasinya segera dikirim.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bisa kirim hari ini',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bisa banget! Checkout sekarang langsung kita prioritaskan masuk kloter pengiriman hari ini.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kok belum sampai',
    scope: 'all',
    response_type: 'text',
    response_content: 'Mohon ditunggu sebentar kak, mimin bantu follow up langsung ke pihak kurirnya ya!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'paket rusak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Waduh jangan khawatir kak! Kirim video unboxing paketnya ya, kalau terbukti rusak dari kurir kita ganti baru 100%.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'salah kirim',
    scope: 'all',
    response_type: 'text',
    response_content: 'Mohon maaf atas ketidaknyamanannya kak! Fotoin barang yang datang ya, kita tukar dan semua ongkir kita yang tanggung.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kurir nyasar',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sip kak, kasih patokan rumah atau nomor yang bisa dihubungi biar mimin sambungin ke kurirnya.',
    is_active: true,
  },

  // 10. Ucapan Terima Kasih, Santai & Humor (181-200)
  {
    trigger_type: 'contains',
    trigger_value: 'makasih bro',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sama-sama bro! Senang bisa bantu. Sukses terus ya buat kamu 🙌',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'makasih banyak',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sama-sama kak! Terima kasih kembali atas kepercayaannya. Jangan kapok mampir ke sini ya ✨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'terima kasih min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sama-sama kak! Sehat selalu dan lancar rezekinya ya 🙏',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'thanks ya',
    scope: 'all',
    response_type: 'text',
    response_content: 'Anytime kak! Jangan ragu kontak lagi kalau ada hal lain yang perlu dibantu.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'thx bro',
    scope: 'all',
    response_type: 'text',
    response_content: 'Santai sob! You are welcome 👊',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'oke sip',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sip mantap! Ditunggu kabar baiknya ya kak.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'siap min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap komandan! Laksanakan dengan penuh tanggung jawab 😎',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'mantap jiwa',
    scope: 'all',
    response_type: 'text',
    response_content: 'Haha mantap pol bro! Yang terbaik khusus buat kamu lah pokoknya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'keren banget',
    scope: 'all',
    response_type: 'text',
    response_content: 'Makasih pujiannya kak! Makin semangat nih melayani kamu hehe.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'pelayanan bagus',
    scope: 'all',
    response_type: 'text',
    response_content: 'Alhamdulillah makasih testimoninya kak! Kepuasan kamu adalah kebahagiaan kita ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'wkwk',
    scope: 'all',
    response_type: 'text',
    response_content: 'Haha ketawa itu sehat kak, tapi lebih sehat lagi kalau sambil belanja wkwkwk 😂',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'hehe',
    scope: 'all',
    response_type: 'text',
    response_content: 'Senyum itu ibadah kak! Semoga hari ini bawa banyak rezeki ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bercanda min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Santai aja kak, hidup udah pusing jangan dibikin tegang haha!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ngopi dulu',
    scope: 'all',
    response_type: 'text',
    response_content: 'Seruput dulu kopinya kawan ☕ Biar otak tetep encer mikirin cuan!',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'dadah',
    scope: 'all',
    response_type: 'text',
    response_content: 'Sampai jumpa lagi kak! Hati-hati di jalan dan selamat beraktivitas 👋',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'bye bye',
    scope: 'all',
    response_type: 'text',
    response_content: 'Bye kak! See you next time, jangan lupa balik lagi ya.',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'good night',
    scope: 'all',
    response_type: 'text',
    response_content: 'Good night! Mimpi indah ya, semoga besok harinya lebih produktif 🌙',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'semangat min',
    scope: 'all',
    response_type: 'text',
    response_content: 'Makasih banyak kak! Kamu juga harus tetep semangat pantang mundur ya 💪🔥',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'salam kenal',
    scope: 'all',
    response_type: 'text',
    response_content: 'Salam kenal juga kak! Semoga silaturahmi kita bawa berkah dan rezeki luas 🙏',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'sukses selalu',
    scope: 'all',
    response_type: 'text',
    response_content: 'Aamiin ya rabbal alamin! Sukses, sehat, dan jaya selalu juga buat kamu sekeluarga kak 🚀',
    is_active: true,
  },

  // 11. Obrolan Manis & Perhatian Pasangan (Khusus Indah / Pacar: +62 852-1614-9732)
  {
    trigger_type: 'contains',
    trigger_value: 'sayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya sayang? Kenapa nih? Ada apa gerangan cintaku ❤️ Ada yang mau diceritain?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya ayanggg, hadir! Kangen ya? Hehe ada apa nih sayangku?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'ndah',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Iya sayang, kenapa tuh? Jangan cemberut ya, mau cerita apa hari ini?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'udah makan belum sayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Udah kok sayang, kamu sendiri udah makan belum? Jangan telat makan ya nanti masuk angin 🥺',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'lagi apa sayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Lagi mikirin kamu nih hehe. Kamu lagi ngapain sekarang sayang? Sibuk gak?',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'jangan begadang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap sayang! Gak begadang kok, kamu juga cepet istirahat ya jangan tidur kemaleman ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'pagi sayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Pagi juga kesayanganku! Semangat ya jalanin hari ini, sarapan dulu jangan lupa ☕❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'malam sayang',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Malam sayang! Selamat istirahat ya, mimpi indah dan sampai ketemu besok 🌙✨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'love you',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Love you more sayang! Selalu ada buat kamu ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kangen kamu',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Kangen bangett juga! Nanti kalau ada waktu luang kita jalan bareng ya sayang 🌹',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'sayang kamu',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Aku juga sayang banget sama kamu, jangan pernah ragu ya ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'jemput ya',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Siap sayang! Kabari aja jam berapa dan di mana, nanti aku jemput ya 🛵💨',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'jalan yuk',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Ayo sayang! Mau kulineran ke mana hari ini? Nanti kita atur ya ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'kapan ketemu',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Secepatnya ya sayang. Nanti kita cocokin jadwal bareng, aku juga kangen banget ❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'miss you',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Miss you so much more sayang! Sehat-sehat ya di sana 🥺❤️',
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: 'aku ngambek',
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: 'Yah kok ngambek sih sayang? Jangan cemberut dong, mau jajan apa nanti aku beliin biar senyum lagi 🥺🍧',
    is_active: true,
  },
]
