import type { CreateRulePayload } from '@/api/bot'

export const MEGA_PROMPT_200_AUTO_REPLIES = "### PERAN & TUJUAN\nKamu adalah Pakar Percakapan WhatsApp (WhatsApp Interaction Designer & Copywriter Indonesia) yang memiliki pemahaman mendalam tentang gaya percakapan santai, akrab, manusiawi, dan anti-robot.\nTugasmu adalah menganalisis DUA BERKAS LAMPIRAN CHAT WHATSAPP yang kuunggah:\n1. \"PENCARI LOKER\" (Berisi riwayat chat tongkrongan kampus / pemuda Medan bersama Eka Syarif Maulana S.Kom dan rekan-rekannya).\n2. \"Indah 🧕🌿💝\" (Berisi riwayat chat personal dari NOMOR KHUSUS: +62 852-1614-9732).\n\nBerdasarkan analisis kedua berkas tersebut, tugas utamamu adalah menghasilkan DATA DUMP 200 ATURAN BALASAN OTOMATIS (Auto-Reply Rules) dalam format JSON Array murni yang 100% cocok untuk di-import langsung ke sistem WhatsApp Bot kami.\n\n---\n\n### ANALISIS GAYA BAHASA DARI DUA SUMBER (WAJIB DITERAPKAN)\n\n1. REFERENSI SUMBER 1: \"PENCARI LOKER\" (Gaya Chat Teman, Tongkrongan & Sehari-hari):\n   - Persona: Eka Syarif Maulana S.Kom, santai, ceplas-ceplos, cerdas, solutif, akrab, humoris, to the point.\n   - Kosakata & Karakter Obrolan: Santai khas Medan / gaul Indonesia (\"wkwk / wkwkwk\", \"santai aja\", \"ngopi dulu\", \"gas\", \"otw\", \"bentar\", \"aman itu\", \"kabari aja\", \"kenapa tuh\", \"ada apa nih\", \"pigi\", \"jumpalah\", \"mantap kali\", \"siap bro\").\n   - Tone: Sangat santai, tidak pernah kaku, responsif, bersahabat, to the point.\n   - LARANGAN KERAS: Dilarang keras memakai gaya customer service formal robotik (DILARANG: \"Ada yang bisa dibantu?\", \"Operasional 08.00-22.00 WIB\", \"Semoga harimu menyenangkan ✨\", \"Silakan tunggu sebentar ya kak\").\n\n2. REFERENSI SUMBER 2: \"Indah 🧕🌿💝\" (Gaya Chat Hangat untuk NOMOR KHUSUS: +62 852-1614-9732):\n   - Persona: Penuh perhatian, hangat, lembut, menyayangi, santai, dan bersahabat.\n   - Topik & Diksi: Perhatian sehari-hari (\"udah makan belum?\", \"lagi apa?\", \"jangan begadang ya\", \"istirahat dulu\", \"semangat ya hari ini\", \"kangen nih\", \"nanti kita jalan ya\", \"hati-hati di jalan\").\n   - LARANGAN KERAS: Gunakan label 'Nomor Khusus' secara konsisten. Dilarang merespon seperti robot atau CS formal! Respon harus terdengar seperti orang asli yang sedang membalas chat secara spontan dan hangat.\n\n---\n\n### STRUKTUR PEMBAGIAN 200 PEMICU (JSON):\n- Kategori A: 150 Pemicu Umum / Global (Adopsi gaya dari PENCARI LOKER):\n  1. Sapaan Waktu & Salam (Pagi, Siang, Sore, Malam, Halo, Assalamualaikum, Oy, Woi, dll. - 25 pemicu)\n  2. Sapaan Singkat & Panggilan (P, Ping, Tes, Min, Gan, Bro, Bang, Cuy, dll. - 25 pemicu)\n  3. Keberadaan, Janji & Posisi (Lagi di mana, Posisi, Di kos gak, Otw, Jumpa di mana, dll. - 20 pemicu)\n  4. Tongkrongan, Ngopi, Mabar & Santai (Ngopi yuk, Nongkrong, Mabar, Push rank, Wkwk, dll. - 25 pemicu)\n  5. Urusan, Kampus, Pelatihan & Pekerjaan (Gimana kabar, Wisuda, Jurnal, Info loker, dll. - 20 pemicu)\n  6. Transaksi, Transfer & Rekening (Berapaan, Minta no rek, Bisa transfer, Bukti transfer, dll. - 15 pemicu)\n  7. Penutup, Terima Kasih & Pamit (Makasih bro, Mantap kali, Santai aja, Cabut dulu, dll. - 20 pemicu)\n\n- Kategori B: 50 Pemicu NOMOR KHUSUS (+62 852-1614-9732):\n  1. Sapaan & Keberadaan (Pagi, Siang, Malam, Lagi apa, Di mana sekarang, dll. - 10 pemicu)\n  2. Perhatian Harian & Makan (Udah makan belum, Jangan lupa sarapan, Jajan yuk, dll. - 10 pemicu)\n  3. Istirahat, Capek & Kesehatan (Jangan begadang, Istirahat ya, Capek ya, Tidur yuk, dll. - 10 pemicu)\n  4. Rindu, Temu & Jalan (Kangen, Kapan ketemu, Jalan yuk, Jemput ya, Otw ya, dll. - 10 pemicu)\n  5. Semangat, Mood & Perhatian (Semangat ya hari ini, Jangan cemberut, Senyum dong, dll. - 10 pemicu)\n\n---\n\n### ATURAN FORMAT OUTPUT (RAW JSON ARRAY MURNI):\n- Hasilkan HANYA valid JSON Array tanpa teks pengantar, penutup, atau markdown pembungkus di luar JSON.\n- Struktur setiap objek:\n  {\n    \"trigger_type\": \"contains\", // atau \"exact\"\n    \"trigger_value\": \"<kata_kunci>\",\n    \"recipient_jid\": \"6285216149732@s.whatsapp.net\", // WAJIB: Isi '6285216149732@s.whatsapp.net' KHUSUS untuk Kategori B (Nomor Khusus), atau kosongkan \"\" untuk Kategori A (Umum/Global)\n    \"scope\": \"all\",\n    \"response_type\": \"text\",\n    \"response_content\": \"<teks_balasan_sesuai_analisis>\",\n    \"is_active\": true\n  }\n\nSekarang, baca kedua berkas (\"PENCARI LOKER\" & \"Indah 🧕🌿💝\"), dan hasilkan 200 data objek JSON lengkap tersebut!"

export const DEFAULT_200_AUTO_REPLIES: CreateRulePayload[] = [
  {
    trigger_type: 'contains',
    trigger_value: "selamat pagi",
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi bro! Udah bangun kau? Jangan lupa ngopi dulu lah wkwk",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pagi bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi! Semangat kali hari ini, gas ke mana kita?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pagi ges",
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi gess, udah pada melek belum ni?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pagi kawan",
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi kawan! Aman kan hari ini? Kabari aja kalau ada apa-apa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pagi",
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi! Santai dulu, ngopi-ngopi lah biar gak oleng wkwk",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat siang",
    scope: 'all',
    response_type: 'text',
    response_content: "Siang! Panas kali ya cuaca hari ini, santai aja ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siang bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Siang bro! Udah makan siang belum? Ada kabar apa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siang ges",
    scope: 'all',
    response_type: 'text',
    response_content: "Siang gess! Lagi pada di mana nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siang",
    scope: 'all',
    response_type: 'text',
    response_content: "Siang! Santai aja, ada perlu apa nih bro?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat sore",
    scope: 'all',
    response_type: 'text',
    response_content: "Sore bro! Udah jam santai nih, gimana hari ini aman?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sore bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Sore! Baru balik kerja/kampus kah? Santai dulu lah.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sore ges",
    scope: 'all',
    response_type: 'text',
    response_content: "Sore gess! Ngumpul di mana sore ini?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sore",
    scope: 'all',
    response_type: 'text',
    response_content: "Sore juga! Ada apa nih tumben chat sore-sore?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat malam",
    scope: 'all',
    response_type: 'text',
    response_content: "Malam bro! Belum tidur kau? Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "malam bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Malam! Lagi santai di kos kah? Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "malam ges",
    scope: 'all',
    response_type: 'text',
    response_content: "Malam gess! Masih pada melek rupanya wkwk",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "malam",
    scope: 'all',
    response_type: 'text',
    response_content: "Malam juga! Santai, ada hal penting kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "assalamualaikum",
    scope: 'all',
    response_type: 'text',
    response_content: "Waalaikumsalam bro! Sehat kan? Ada kabar apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "assalamualaikum bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Waalaikumsalam! Gimana kabar, aman semuanya?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "samlikum",
    scope: 'all',
    response_type: 'text',
    response_content: "Waalaikumsalam wkwk, tumben singkat kali salam kau.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "salam",
    scope: 'all',
    response_type: 'text',
    response_content: "Salam juga bro! Santai, kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "halo bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Halo bro! Ada apa nih? Cerita lah santai.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "halo ges",
    scope: 'all',
    response_type: 'text',
    response_content: "Halo gess! Nongkrong di mana nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "halo",
    scope: 'all',
    response_type: 'text',
    response_content: "Halo juga! Santai, ada kabar apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "hai",
    scope: 'all',
    response_type: 'text',
    response_content: "Hai juga! Santai aja, kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: "p",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya woi, kenapa? Langsung to the point aja santai wkwk",
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: "ping",
    scope: 'all',
    response_type: 'text',
    response_content: "Hadirr bro! Santai, kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: "pe",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya ada apa? Jangan p doang lah wkwk, cerita langsung.",
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: "tes",
    scope: 'all',
    response_type: 'text',
    response_content: "Masuk kok bro, aman. Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'exact',
    trigger_value: "test",
    scope: 'all',
    response_type: 'text',
    response_content: "Aman 100%, pesanmu sampai. Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "woi",
    scope: 'all',
    response_type: 'text',
    response_content: "Woi juga! Kenapa heboh kali kau wkwk?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "oi",
    scope: 'all',
    response_type: 'text',
    response_content: "Oi! Ada apa nih? Santai lah.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "oy",
    scope: 'all',
    response_type: 'text',
    response_content: "Oy bro! Masih hidup kan? Wkwkwk ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya bro, kenapa tuh? Kabari aja santai.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "cuy",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya cuy, santai aja. Ada bahasan apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gan",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya gan, santai aja kayak sama siapa aja wkwk. Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "min",
    scope: 'all',
    response_type: 'text',
    response_content: "Bukan mimin robot ini wkwk, santai aja bro. Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bang",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya bang, aman. Kenapa tuh? Langsung aja kabari.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lur",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya lur, santai. Gimana kabarmu hari ini?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mas",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya mas, aman itu. Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ketua",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap ketua! Ada arahan apa hari ini wkwk?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bos",
    scope: 'all',
    response_type: 'text',
    response_content: "Bukan bos ini wkwk, kawan sendiri. Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kawan",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya kawan, santai aja. Ceritakan lah ada apa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "info",
    scope: 'all',
    response_type: 'text',
    response_content: "Info apa nih? Spill lah dulu biar paham.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "spill",
    scope: 'all',
    response_type: 'text',
    response_content: "Spill apa nih bro? Jangan bikin penasaran lah wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "hadir",
    scope: 'all',
    response_type: 'text',
    response_content: "Mantap, siap monitor! Ada pergerakan apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "permisi",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya santai aja bro, masuk aja gak dikunci wkwk. Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "punten",
    scope: 'all',
    response_type: 'text',
    response_content: "Mangga lur, santai aja. Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "helo",
    scope: 'all',
    response_type: 'text',
    response_content: "Helo juga bro! Kabari aja santai.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "yoo",
    scope: 'all',
    response_type: 'text',
    response_content: "Yoo wazzup! Ada kabar apa nih hari ini?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi di mana",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi santai di tempat nih, kenapa tuh? Mau jumpa kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "di mana kau",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di kos nih santai, kenapa tuh woi?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "di mana bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di tempat biasa nih bro, mau ke sini kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "posisi",
    scope: 'all',
    response_type: 'text',
    response_content: "Posisi lagi standby di kos nih, kau di mana?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi ngapain",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi santai rebahan sambil mantau hp nih wkwk. Kau lagi apa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sibuk gak",
    scope: 'all',
    response_type: 'text',
    response_content: "Gak terlalu sibuk kok, santai aja. Ada perlu apa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi sibuk ya",
    scope: 'all',
    response_type: 'text',
    response_content: "Aman kok, santai aja. Langsung ceritakan aja bro.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ada di kos",
    scope: 'all',
    response_type: 'text',
    response_content: "Ada nih di kos, pintu gak dikunci masuk aja wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ada di rumah",
    scope: 'all',
    response_type: 'text',
    response_content: "Ada di tempat nih, kenapa tuh? Mau mampir kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bisa jumpa",
    scope: 'all',
    response_type: 'text',
    response_content: "Bisa kali, atur aja waktu sama tempatnya lah.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jumpa di mana",
    scope: 'all',
    response_type: 'text',
    response_content: "Di tempat biasa aja lah biar enak ngobrolnya, gimana?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ayok jumpa",
    scope: 'all',
    response_type: 'text',
    response_content: "Gas lah jumpalah kita, jam berapa enaknya?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "otw",
    scope: 'all',
    response_type: 'text',
    response_content: "Sip hati-hati di jalan ya, kabari kalau dah dekat!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi jalan",
    scope: 'all',
    response_type: 'text',
    response_content: "Aman, jangan ngebut-ngebut ya bro. Kabari nanti.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah sampai",
    scope: 'all',
    response_type: 'text',
    response_content: "Mantap, tunggu bentar ya ku ke depan!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jam berapa",
    scope: 'all',
    response_type: 'text',
    response_content: "Bebas aja, sesuaikan jadwalmu. Kabari kalau udah siap ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tunggu ya",
    scope: 'all',
    response_type: 'text',
    response_content: "Santai aja, gak ke mana-mana kok aku.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bentar ya",
    scope: 'all',
    response_type: 'text',
    response_content: "Oke siap santai aja bro, kutunggu ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tunggu bentar",
    scope: 'all',
    response_type: 'text',
    response_content: "Aman, take your time bro.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bisa telpon",
    scope: 'all',
    response_type: 'text',
    response_content: "Chat dulu aja bro kenapa tuh? Biar kubaca dulu.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ngopi",
    scope: 'all',
    response_type: 'text',
    response_content: "Ayoklah gas ngopi, di mana enaknya nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ayok ngopi",
    scope: 'all',
    response_type: 'text',
    response_content: "Gass, jemputlah kalau bisa wkwk. Di warkop biasa kan?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ngopi yuk",
    scope: 'all',
    response_type: 'text',
    response_content: "Gaspol, jam berapa mau gerak nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "nongkrong",
    scope: 'all',
    response_type: 'text',
    response_content: "Boleh kali, anak-anak yang lain pada ikut gak tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mabar",
    scope: 'all',
    response_type: 'text',
    response_content: "Gass login lah, jangan beban ya wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "login",
    scope: 'all',
    response_type: 'text',
    response_content: "Bentar buka gamenya dulu, tunggu di lobi ya!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "push rank",
    scope: 'all',
    response_type: 'text',
    response_content: "Ayok push rank, tapi jangan bikin turun bintang ya wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "login ml",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap meluncur, invite lah sekarang!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gas mabar",
    scope: 'all',
    response_type: 'text',
    response_content: "Gaspol, jangan afk ya di tengah jalan!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gas",
    scope: 'all',
    response_type: 'text',
    response_content: "Gas terus tanpa rem wkwk! Ke mana kita?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gass",
    scope: 'all',
    response_type: 'text',
    response_content: "Gasslah, jangan wacana doang ya wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ayok",
    scope: 'all',
    response_type: 'text',
    response_content: "Ayoklah, siapa takut. Jam berapa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "yok",
    scope: 'all',
    response_type: 'text',
    response_content: "Yok gerak, kabari kalau udah mau jalan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gaspol",
    scope: 'all',
    response_type: 'text',
    response_content: "Omke gas omke gas wkwk! Mantap kali.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mantap",
    scope: 'all',
    response_type: 'text',
    response_content: "Mantap kali memang, berkelas kawan kita satu ini wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mantap kali",
    scope: 'all',
    response_type: 'text',
    response_content: "Bukan kaleng-kaleng kawan kita wkwkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "keren",
    scope: 'all',
    response_type: 'text',
    response_content: "Jelas dong, siapa dulu wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "wkwk",
    scope: 'all',
    response_type: 'text',
    response_content: "Malah ketawa kau wkwk, ada-ada aja memang.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "wkwkwk",
    scope: 'all',
    response_type: 'text',
    response_content: "Ngakak kali ya wkwk, dahlah capek ketawa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "haha",
    scope: 'all',
    response_type: 'text',
    response_content: "Wkwk ketawa lepas kali kau ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "anjay",
    scope: 'all',
    response_type: 'text',
    response_content: "Anjayy kelas kali bahasanya wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bjir",
    scope: 'all',
    response_type: 'text',
    response_content: "Bjirr kaget aku wkwk, kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "njir",
    scope: 'all',
    response_type: 'text',
    response_content: "Njirr bisa gitu ya wkwk, aneh-aneh aja kelakuan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "santai",
    scope: 'all',
    response_type: 'text',
    response_content: "Santai kali hidup ini, nikmati dulu lah ngopi-ngopi.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "santai aja",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya santai aja bro, gak usah tegang-tegang kali.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "gimana kabar",
    scope: 'all',
    response_type: 'text',
    response_content: "Alhamdulillah aman sehat sentosa wkwk, kabar kau gimana?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "apa kabar",
    scope: 'all',
    response_type: 'text',
    response_content: "Kabar baik bro! Masih aman terkendali, ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sehat kan",
    scope: 'all',
    response_type: 'text',
    response_content: "Sehat walafiat alhamdulillah, kau sehat juga kan?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "aman kan",
    scope: 'all',
    response_type: 'text',
    response_content: "Aman terkendali bro, gak ada kendala. Kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ada apa nih",
    scope: 'all',
    response_type: 'text',
    response_content: "Gak ada apa-apa sih, santai aja. Tumben kau nanya wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kenapa tuh",
    scope: 'all',
    response_type: 'text',
    response_content: "Itulah ceritanya wkwk, panjang kali kalau diceritakan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ada kabar apa",
    scope: 'all',
    response_type: 'text',
    response_content: "Gak ada kabar aneh-aneh sih, aman semua. Kau ada info baru?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "wisuda",
    scope: 'all',
    response_type: 'text',
    response_content: "Mantap wisuda, jangan lupa traktiran wisudanya lah wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "skripsi",
    scope: 'all',
    response_type: 'text',
    response_content: "Semangat pejuang skripsi, kerjakan jangan ditunda-tunda deadline wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jurnal",
    scope: 'all',
    response_type: 'text',
    response_content: "Jurnal aman itu, cari template yang pas biar langsung tembus!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kampus",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di kampus kah kau? Mau ngurus berkas apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "umsu",
    scope: 'all',
    response_type: 'text',
    response_content: "UMSU tercinta wkwk, mau ke biro atau ke fakultas nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "skl",
    scope: 'all',
    response_type: 'text',
    response_content: "Ambil SKL jangan lupa fotocopy rangkapnya ya bro, biar gak bolak-balik.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ijazah",
    scope: 'all',
    response_type: 'text',
    response_content: "Udah keluar ijazahnya? Mantap kali, gas lamar kerja!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pelatihan",
    scope: 'all',
    response_type: 'text',
    response_content: "Pelatihan apa tuh? Baguslah nambah-nambah sertifikat buat CV.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sertifikat",
    scope: 'all',
    response_type: 'text',
    response_content: "Lumayan kali nambah portofolio itu, modals sikit gak apa yang penting berilmu.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "loker",
    scope: 'all',
    response_type: 'text',
    response_content: "Ada loker info kah? Bagi-bagi lah ke grup biar berkah wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kerjaan",
    scope: 'all',
    response_type: 'text',
    response_content: "Kerjaan aman lancar kan? Jangan terlalu stres, bawa santai aja.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "info kerja",
    scope: 'all',
    response_type: 'text',
    response_content: "Kalau ada info kerjaan cocok kabari ya bro, saling bantu kita.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "cv",
    scope: 'all',
    response_type: 'text',
    response_content: "CV buat yang rapi to the point, jangan kebanyakan teks bertele-tele.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "portofolio",
    scope: 'all',
    response_type: 'text',
    response_content: "Portofolio bikin yang kelihatan hasilnya langsung, biar HRD tertarik.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lamaran",
    scope: 'all',
    response_type: 'text',
    response_content: "Bismillah gas kirim lamarannya, semoga rezeki ya bro!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "info loker",
    scope: 'all',
    response_type: 'text',
    response_content: "Pantau terus grup loker, mana tau ada yang nyangkut rezeki.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kantor",
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di kantor kah? Semangat cari nafkah bro!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "interview",
    scope: 'all',
    response_type: 'text',
    response_content: "Interview tenang aja, jawab santai tapi tegas dan percaya diri!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "harga",
    scope: 'all',
    response_type: 'text',
    response_content: "Mau tanya harga yang mana nih bro? Kasih tau aja detailnya biar kucekkan nanti.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "berapaan",
    scope: 'all',
    response_type: 'text',
    response_content: "Tergantung kebutuhanmu bro, santai aja harganya bersahabat kok. Mau yang mana?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "berapa harga",
    scope: 'all',
    response_type: 'text',
    response_content: "Sebutkan aja mau yang varian apa bro, nanti kuberi rincian lengkapnya ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "berapa biayanya",
    scope: 'all',
    response_type: 'text',
    response_content: "Biayanya terjangkau kali bro, aman di kantong. Mau buat keperluan apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pricelist",
    scope: 'all',
    response_type: 'text',
    response_content: "Bisa dicek bro, ada paket hemat sampai lengkap. Mau kukirim detailnya?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "cara pesan",
    scope: 'all',
    response_type: 'text',
    response_content: "Gampang kali, tinggal infokan maunya apa nanti langsung diproseskan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "cara order",
    scope: 'all',
    response_type: 'text',
    response_content: "Tinggal list pesanannya aja bro, nanti kuuruskan sampai siap.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mau order",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap gas, mau pesan apa aja nih? Rincikan ya bro.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "rek",
    scope: 'all',
    response_type: 'text',
    response_content: "Bisa transfer ke BCA / Mandiri / Dana bro. Mau nomor rekening yang mana?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "nomor rekening",
    scope: 'all',
    response_type: 'text',
    response_content: "Nanti kukirim nomor rekeningnya ya bro, santai aja.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "no rek",
    scope: 'all',
    response_type: 'text',
    response_content: "Sip bentar ya kukirim no rek-nya, jangan salah transfer ya wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bisa transfer",
    scope: 'all',
    response_type: 'text',
    response_content: "Bisa banget bro, transfer antar bank atau e-wallet aman semua.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bukti transfer",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap, kalau udah transfer kirimkan bukti fotonya ke sini ya bro!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah transfer",
    scope: 'all',
    response_type: 'text',
    response_content: "Mantap makasih banyak bro! Kucek dulu ya, nanti langsung kukabari.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pembayaran",
    scope: 'all',
    response_type: 'text',
    response_content: "Metode pembayaran fleksibel bro, transfer bank atau e-wallet siap semua.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makasih",
    scope: 'all',
    response_type: 'text',
    response_content: "Sama-sama bro! Santai aja kayak sama siapa aja wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makasih ya",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya sama-sama, aman itu. Kabari aja kalau butuh apa-apa lagi.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makasih banyak",
    scope: 'all',
    response_type: 'text',
    response_content: "Sama-sama bro, senang bisa bantu! Santai aja.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "thanks",
    scope: 'all',
    response_type: 'text',
    response_content: "You're welcome bro! Santai aja ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tengkyu",
    scope: 'all',
    response_type: 'text',
    response_content: "Sama-sama kawan! Sukses terus ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "thank you",
    scope: 'all',
    response_type: 'text',
    response_content: "Anytime bro! Santai aja.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "trims",
    scope: 'all',
    response_type: 'text',
    response_content: "Sama-sama! Aman selalu ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sama-sama",
    scope: 'all',
    response_type: 'text',
    response_content: "Sip mantap, kompak selalu kita!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "santai aja bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Pastilah, hidup dibawa santai biar gak cepat tua wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sip",
    scope: 'all',
    response_type: 'text',
    response_content: "Sip mantap, kabari lagi kalau ada info ya!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "oke",
    scope: 'all',
    response_type: 'text',
    response_content: "Oke siap, meluncur!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siap",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap laksanakan ketua wkwk!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siap bro",
    scope: 'all',
    response_type: 'text',
    response_content: "Siap, aman terkendali pokoknya!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "dahlah",
    scope: 'all',
    response_type: 'text',
    response_content: "Dahlah capek mikir wkwk, ngopi dulu lah kita.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pamit dulu",
    scope: 'all',
    response_type: 'text',
    response_content: "Sip hati-hati ya bro, jangan lupa kabari kalau udah sampai.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tidur dulu",
    scope: 'all',
    response_type: 'text',
    response_content: "Tidur yang nyenyak bro, jangan lupa baca doa wkwk.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "cabut dulu",
    scope: 'all',
    response_type: 'text',
    response_content: "Oke hati-hati di jalan bro, see you!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "hati-hati",
    scope: 'all',
    response_type: 'text',
    response_content: "Iya makasih bro, kau juga hati-hati di sana ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "see you",
    scope: 'all',
    response_type: 'text',
    response_content: "See you bro! Sampai jumpa lagi ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bye",
    scope: 'all',
    response_type: 'text',
    response_content: "Bye bro, jaga kesehatan ya!",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "pagi",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi juga! Udah bangun ya? Jangan lupa sarapan dulu yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat pagi",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Pagi juga! Semangat ya jalanin hari ini, semoga semuanya lancar.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "siang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Siang! Lagi istirahat siang kah? Jangan lupa makan yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat siang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Siang juga! Panas banget hari ini, jaga kesehatan ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sore",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Sore! Gimana hari ini? Udah santai kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat sore",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Sore juga! Udah mau pulang ya? Hati-hati di jalan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "malam",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Malam! Lagi santai kah sekarang? Ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "selamat malam",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Malam juga! Selamat istirahat ya, tidur yang nyenyak.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "halo",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Halo juga! Kenapa nih tumben, ada cerita apa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "hai",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Hai juga! Lagi ngapain sekarang? Sibuk kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi apa",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi santai di tempat nih, kamu sendiri lagi ngapain?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi ngapain",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Gak lagi ngapa-ngapain sih, lagi santai aja. Kamu lagi sibuk ya?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "di mana sekarang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di tempat nih santai, kamu di mana sekarang?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah pulang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah kok tadi, kamu udah di rumah belum? Hati-hati di jalan ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah sampai",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah sampai dengan aman kok, makasih ya udah nanyain.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sibuk gak",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Gak kok, santai aja. Mau ngobrol kah?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ada waktu gak",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Ada kok, kenapa tuh? Cerita aja santai.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lagi di mana",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di kos nih santai, kenapa tuh?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bisa telpon",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Lagi di luar nih, chat dulu yaa ada apa nih?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kabar gimana",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Alhamdulillah baik dan sehat, kamu sendiri gimana kabarnya?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah makan",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah kok tadi, kamu sendiri udah makan belum? Jangan telat yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "udah makan belum",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah barusan, kamu makan apa hari ini? Jangan lupa makan yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makan siang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah tadi makan siang, kamu jangan lupa makan juga yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sarapan",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah sarapan tadi, kamu juga sarapan dulu biar ada tenaga.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makan malam",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah kok, kamu mau makan malam apa nih hari ini?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jangan lupa makan",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa siap, kamu juga ya jangan sampai telat makan.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "makan yuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Ayok, mau makan di mana nih? Nanti kita atur yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jajan yuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Boleh bangett, lagi pengen jajan apa nih hari ini?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "minum air",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa udah minum, kamu juga banyakin minum air putih yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "mau makan apa",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Bebas aja sih, yang penting enak dan kenyang hehe. Kamu pengen apa?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jangan begadang",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa siap gak begadang kok, kamu juga tidur cepatan yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "istirahat ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa makasih udah ngingetin, kamu juga istirahat yang cukup yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "capek ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Lumayan sih hari ini, tapi aman kok. Kamu capek juga gak?",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "lelah",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Rebahan dulu gih, jangan dipaksain yaa kalau lagi capek.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tidur yuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Ayok tidur, udah malam juga nih. Selamat istirahat yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "tidur ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa selamat tidur yaa, semoga tidurnya nyenyak.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "bobo",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa bobo dulu gih, mimpi indah yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ngantuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Tidur gih kalau udah ngantuk, jangan dipaksain melek yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "sehat kan",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Alhamdulillah sehat kok, kamu jaga kesehatan juga ya di sana.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jangan sakit",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa gak kok, kamu juga ya jangan kecapekan biar gak drop.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kangen",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa kangen jugaa, nanti kalau pas senggang kita ketemu yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "kapan ketemu",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Secepatnya yaa, nanti kita cocokin waktu bareng-bareng.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "ketemu yuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Ayok bangett, kabari aja kalau kamu lagi ada waktu luang.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jalan yuk",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Bolehh, mau jalan ke mana nih enaknya? Nanti kita rencanain ya.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jemput ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Bisaa, kabari aja jam berapa dan lokasinya di mana yaa.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "otw ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Iyaa hati-hati di jalan yaa, kabari kalau udah dekat.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "semangat ya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Makasih banyak yaa! Kamu juga harus tetap semangat hari ini.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "semangat kerjanya",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Siap makasih yaa, kamu juga lancar-lancar kerjanya hari ini.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "jangan ngambek",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Gak ngambek kok hehe, kamu juga jangan cemberut dong senyum.",
    is_active: true,
  },
  {
    trigger_type: 'contains',
    trigger_value: "senyum dong",
    recipient_jid: '6285216149732@s.whatsapp.net',
    scope: 'all',
    response_type: 'text',
    response_content: "Udah senyum kok nih hehe, kamu juga senyum ya biar harinya manis.",
    is_active: true,
  },
]
